config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get       'login'     => 'sessions#new'
  post      'login'     => 'sessions#create'
  delete    'logout'    => 'sessions#destroy'
  get       'main_page/home'
  get       'main_page/sign_in', as: 'sign_in_main_page'

  resources :boards
  resources :users
  resources :topic_posts
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
    

  root 'main_page#home'

  

end

app/models/user.rb
class User < ActiveRecord::Base
    # copied from www.railstutorial.org, chapter 6
    # it ain't perfect, but we can deal with that later
    # does what it says: downcase the email before we save
    # this is the ONLY ENSURANCE we have that the database won't be
    # corrupted.
    before_save { self.email = email.downcase }
    # This matches emails. Not 100% to spec, but rational
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    # An email shall be present, no logner than 255 characters (DB restriction),
    # follows the regex format, and its uniqueness is indifferent to case
    validates :email, presence: true, length: { maximum: 255},
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    # Matches an alphanumeric name
    VALID_NAME_REGEX = /\A[\w]+/
    # A name shall be present, at least one character long and no more than 255
    validates :name, presence: true,
                     length: { minimum: 1, maximum: 255 },
                     format: { with: VALID_NAME_REGEX }
    validates :password, presence: true,
                         length: { minimum: 6 }
    # this does all the machinery for a secure password, in conjunction with Bcrypt
    has_secure_password
    # This is used for the remember session functionality
    attr_accessor :remember_token, :activation_token, :reset_token
    before_save   :downcase_email
    before_create :create_activation_digest
    has_many :replies, class_name: "TopicPost"
    
    # member method: encrypts a string
    def User.digest( string )
        # sets the encryption cost to the minimum cost if we are in dev mode,
        # basically
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        # use the BCrypt engine to encrypt the string
        BCrypt::Password.create( string, cost: cost )
    end
    
    def User.new_token
        # generate a random base 64 string as the token
        SecureRandom.urlsafe_base64
    end
    
    def remember
        # generate a new token. This is the ONLY PLACE where the remember_token
        # is reset. VERY IMPORTANT TO REMEMBER
        self.remember_token = User.new_token
        # we got the remember_digest from the database, I think?
        # whatever: encrypt the new token, store it in the digest
        update_attribute( :remember_digest, User.digest( remember_token ) )
    end
    
    # Returns true of the given token matches the given attribute digest.
    def authenticated?( attribute, token )
        # In this context, "password" is taken to be a generalization;
        # we are using the authentication code of BCrypt to authenticate
        # something that isn't STRICTLY speaking 'the' password.
        digest = send("#{attribute}_digest")
        # ^ Ruby metaprogramming hoodoo ^
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end
    
    def forget
        # clear the remember token
        update_attribute(:remember_digest, nil)
    end
    
    def activate
        update_attribute(:activated, true)
        update_attribute(:activated_at, Time.zone.now)
    end
    
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end
    
    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest, User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end
    
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end
    
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end
    
    private
        def downcase_email
            self.email = email.downcase
        end
        
        def create_activation_digest
            self.activation_token  = User.new_token
            self.activation_digest = User.digest(activation_token)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # Before edit and update, make sure a user in logged in
    before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
    # ^ method ^     |              ^ options hash, with a hash value
    #                ^ symbol of target method
    # Ensure that the correct user is logged in on edit and update
    before_action :correct_user,   only: [:edit, :update]
    before_action :admin_user, only: :destroy
    
    # Serves up the index page, providing a variable with an array
    # of all users in the database
    def index
        @users = User.paginate( page: params[:page])
    end
    # Serves up the individual user page, providing a variable with the
    # user to extract information from
    def show
       @user = User.find(params[:id]) 
    end
    # Serves up the new page and provides a blank dummy user variable.
    # This is partly due to the template having a partial that takes a
    # User variable as input used for BOTH new and edit
    def new
        @user = User.new        
    end
    
    def create
        # Use strong parameters to admit only permitted params
        @user = User.new( user_params )
        # If the user in play manages to save...
        if @user.save
            @user.send_activation_email
            # Add a message to the flash hash
            flash[:info] = "Please check your email to activate your account"
          # ^ hash  ^ key      ^ message
            redirect_to root_url
        else
            # OTHERWISE, loop back to the new page.
            # The local @user object has not changed, and the save method
            # with populate the User object's errors hash with information.
            # The page will take care of displaying this info
            render 'new'
            
        end        
    end

    def edit
        @user = User.find(params[:id])
    end
    
    def update
        # Notice the parallelism with the create method
        @user = User.find(params[:id])
        # Instead of save, we use the update_attributes method
        # which is way longer and not at all similar looking :P
        if @user.update_attributes(user_params)
            flash[:success] = "Profile updated."
            redirect_to @user
        else
            # We also render the edit page instead of the new page, naturally
            render 'edit'
        end
    end
    
    def destroy
        User.find(params[:id]).destroy
        flash[:success] = "User deleted"
        redirect_to users_url
    end
    
    private
        # This method deals with strong parameters.
        def user_params
            params.require(:user).permit( :name, :email, :password,
                                          :password_confirmation )
        end
        # This makes sure that actions only logged in users should have
        # access to will only be done by logged in users
        def logged_in_user
            # Nothing happens, unless...
            unless logged_in?
                # The user is logged in, and then we store the target of
                # their request
                store_location
                # Tell them they must log in using the flash hash
                flash[:danger] = "Please log in."
                # And redirect to the login page
                redirect_to login_url
            end
        end
        # Make sure the correct user is using the controller
        def correct_user
            @user = User.find(params[:id])
            # This action is simply illegal if a user tries to target
            # actions controlled by another user, so we go to the root
            # ...for now
            redirect_to(root_url) unless  current_user?(@user)
        end
        
        def admin_user
            redirect_to(root_url) unless current_user && current_user.admin?
        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<h4><%= link_to user.name, user_path(user) %></h4>
<% if current_user.admin? and !current_user?(user) %>
    <%= link_to "delete", user, method: :delete,
        data: { confirm: "You sure?" } %>
<% end %>
<% if user != @users.last %>
    <hr></hr>
<% end %>

app/views/users/edit.html.erb
<div class="tile wide">

    <h1>Update your Information</h1>

    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        
        <%= f.label :name, class: "label" %>
        <br/>
        <%= f.text_field :name, class: "wide field" %>
        <br/>
        <%= f.label :email, class: "label" %>
        <br/>
        <%= f.email_field :email, class: "wide field" %>
        <br/>
        <%= f.label :password, class: "label" %>
        <br/>
        <%= f.password_field :password, class: "wide field" %>
        <br/>
        <%= f.label :password_confirmation, class: "label" %>
        <br/>
        <%= f.password_field :password_confirmation, class: "wide field" %>
        <br/>
        <%= f.submit "Save Changes", class: "btn_blank label" %>
    <% end %>
</div>

app/views/users/index.html.erb
<% content_for :header_left  do %>
    <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user), class: "button" %>
    <% end %>
<% end %>

<% content_for :header_title  do %>
    <h1>Users</h1>
<% end %>

<% content_for :header_right  do %>
    <% if logged_in? %>
        <%= link_to "Log Out", logout_path, method: "delete", class: "button" %>
        <%= link_to "Profile", user_path(current_user), class: "button" %>
    <% end %>
    <%= link_to "Home", boards_path, class: "button" %>
<% end %>
<%= render 'layouts/header' %>



<div class="content_field">
    <div class="sidebar_container left">
        <div class="sidebar left"></div>
    </div>
    <div class="content_container">
        <div class="tile content">
            <%= will_paginate %>
        </div>
        <div class="tile no_border">
            <% if @users.any? %>
                <% @users.each do |user| %>                    
                    <a class="list_item" href=<%=user_path(user)%>>
                        <h3 class="content_division"><%= user.name %></h3>
                        <div class="content_division"><%= user.email %></div>
                    </a>                    
                <% end %>
            <% end %>
        </div>
        <div class="tile content">
            <%= will_paginate %>
        </div>
    </div>
    <div class="sidebar_container right">
        <div class="sidebar right"></div>
    </div>
</div>

app/views/users/new.html.erb
<div class="tile wide">

    <h1>Sign Up</h1>

    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        
        <%= f.label :name, class: "label" %>
        <br/>
        <%= f.text_field :name, class: "wide field" %>
        <br/>
        <%= f.label :email, class: "label" %>
        <br/>
        <%= f.email_field :email, class: "wide field" %>
        <br/>
        <%= f.label :password, class: "label" %>
        <br/>
        <%= f.password_field :password, class: "wide field" %>
        <br/>
        <%= f.label :password_confirmation, class: "label" %>
        <br/>
        <%= f.password_field :password_confirmation, class: "wide field" %>
        <br/>
        <%= f.submit "Create New Account", class: "btn_blank label" %>
    <% end %>
</div>

app/views/users/show.html.erb
<% content_for :header_left  do %>
    <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user), class: "button" %>
    <% end %>
<% end %>

<% content_for :header_title  do %>
    <h1><%= @user.name %></h1>
<% end %>

<% content_for :header_right  do %>
    <% if logged_in? %>
        <%= link_to "Log Out", logout_path, method: "delete", class: "button" %>
        <%= link_to "Profile", user_path(current_user), class: "button" %>
        <%= link_to "edit", edit_user_path(current_user), class: "button" %>
        <%= link_to "users", users_path, class: "button" %>
    <% else %>
        <%= link_to "Log In", login_path, class: "button" %>
    <% end %>
    <%= link_to "Home", boards_path, class: "button" %>
<% end %>
<%= render 'layouts/header' %>


<div class="content_field">
    <div class="sidebar_container left">
        <div class="sidebar left"></div>
    </div>
    <div class="content_container">
        <% if flash.any? %>
            <div class="tile">            
                <% flash.each do |message_type, message| %>
                    <div class="alert alert-<%= message_type %>"><%=message %></div>
                <% end %>
            </div>
        <% end %>
    </div>
    <div class="sidebar_container right">
        <div class="sidebar right"></div>
    </div>
</div>