config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get       'login'     => 'sessions#new'
  post      'login'     => 'sessions#create'
  delete    'logout'    => 'sessions#destroy'
  get       'main_page/home'
  get       'main_page/sign_in', as: 'sign_in_main_page'

  resources :boards
  resources :users
  resources :topic_posts
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
    

  root 'main_page#home'

  

end

app/models/topic_post.rb
class TopicPost < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
  belongs_to :root_post, class_name: "TopicPost"
  
  
  
end

app/controllers/topic_posts_controller.rb
class TopicPostsController < ApplicationController
    
#     def index
#         # I'm not sure about this; indexing posts on their own is a little weird.
#         # I suppose we should select only root posts, because that will
#         # implicitly include all posts, but really posts are indexed on the boards page
#         @topic_post = TopicPost.all
#     end
    
    def show
        # We need pagination logic here; a post is nothing without its context
        # Hopefully the pagination gem we added can help.
        @topic_post = TopicPost.find(params[:id])
    end
    
    def new
        @topic_post = TopicPost.new
        # now we resolve if we are commenting on a topic or starting one
    end
    
    def edit
        @topic_post = TopicPost.find(params[:id])
    end
    
    def create
        @topic_post = TopicPost.new( topic_post_params )
        
        if @topic_post.save
            redirect_to @topic_post
        else
            render 'new'
        end
    end
    
    def update
        @topic_post = TopicPost.find(params[:id])
        
        if @topic_post.update( topic_post_params )
            redirect_to @topic_post
        else
            render 'edit'
        end
        
    end
    
    def destroy
        # the logic here will be different: if we deleted a comment on a topic,
        # then redirect to the appropriate page of the topic. Otherwise,
        # redirect to the containing board. Again , pagination logic.
    end
    
    private
        def topic_post_params
            params.require(:content, :user, :board, :is_topic_post).permit(:root_post)
        end
    
end

app/helpers/topic_posts_helper.rb
module TopicPostsHelper
end

app/views/topic_posts/index.html.erb
<% content_for :header_left  do %>
    <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user), class: "button" %>
        <a class="button" data-method="delete" href= <%=logout_path%> >Log out</a>
    <% end %>
<% end %>

<% content_for :header_title  do %>
    <h1><%= @board.name %></h1>
        <%= @board.description %>
<% end %>

<% content_for :header_right  do %>
    <% if logged_in? %>
        <a class="icon" href= "http://www.google.com" >NT</a>
    <% end %>
    <a class="icon" href= <%=new_board_path( :parent_id => @board.id )%> >NS</a>
<% end %>
<%= render 'layouts/header' %>

<div class="content_field">
    <div class="sidebar_container left">
        <div class="sidebar left"></div>
    </div>
    <div class="content_container">
        <% if @board.children.any? %>
            <div class="tile no_border">
                <% @board.children.each do |child| %>
                    <a class="list_item" href=<%=board_path(child)%>>
                        <h3 class="content_division"><%= child.name %></h3>
                        <div class="content_division"><%= child.description %></div>
                        <!--<%= link_to 'edit', edit_board_path( child ), class: "button" %>
                        <%= link_to 'delete', board_path( child ),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %>-->
                    </a>
                <% end %>
            </div>
        <% end %>
    </div>
    <div class="sidebar_container right">
        <div class="sidebar right"></div>
    </div>
</div>

app/views/topic_posts/show.html.erb
<% content_for :header_left  do %>
    <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user), class: "button" %>
        <a class="button" data-method="delete" href= <%=logout_path%> >Log Out</a>
    <% end %>
<% end %>

<% content_for :header_title  do %>
    <h1>A POST</h1>
<% end %>

<% content_for :header_right  do %>
    Uh oh, how is this gonna work?
    <%= link_to "C", new_topic_post_path( :it_topic_post => true ), class: "icon" %>
    <%= link_to "E",  edit_topic_post_path( @topic_post ), class: "icon" %>
    <%= link_to "H", boards_path, class: "icon" %>
    <!--<a class="icon" href= <%=new_board_path( :parent_id => @board.id )%> >NS</a>
    <a class="icon" href= <%=edit_board_path( @board )%> >E</a>
    <a class="icon" data-method="delete" href= <%=edit_board_path( @board )%> >D</a>
    <a class="icon" href= <%=boards_path%> >H</a>-->
<% end %>

<%= render 'layouts/header' %>


<div class="content_field">
    <div class="sidebar_container left">
        <div class="sidebar left"></div>
    </div>
    <div class="content_container">
        <div class="tile no_border">
            <div class="list_item">
                <h3 class="content_division"><%= @topic_post.user %></h3>
                <div class="content_division"><%= @topic_post.content %></div>
            </div>
        </div>
    </div>
    <div class="sidebar_container right">
        <div class="sidebar right"></div>
    </div>
</div>