config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get       'login'     => 'sessions#new'
  post      'login'     => 'sessions#create'
  delete    'logout'    => 'sessions#destroy'
  get       'main_page/home'
  get       'main_page/sign_in', as: 'sign_in_main_page'

  resources :boards
  resources :users
  resources :topic_posts
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
    

  root 'main_page#home'

  

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :parent, class_name: "Board"
  has_many :children, class_name: "Board",
           dependent: :destroy, foreign_key: "parent_id"
  has_many :topics, class_name: "TopicPost", foreign_key: "board_id"
  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    
    # The index page is identical to the show page, except it
    # always displays the root board "Main"
    def index
        @board = Board.find( 1 )
        @topics = @board.topics
    end
    # Shows the given board, it's subboards, etc.
    def show
        @board = Board.find(params[:id])
        @topics = @board.topics.all
    end
    # Creates a new board under the given parent board.
    # the parent board's ID is given in a hidden field
    def new
        @board = Board.new
        @parent_id = params[:parent_id]
    end
    
    # Similar to the create board page
    def edit
        @board = Board.find(params[:id])
    end
    
    # Errors redirect to the new page
    def create
        @board = Board.new( board_params )
        
        if @board.save
            redirect_to @board
        else
            render 'new'
        end
    end
    # Errors in the form redirect to the edit page
    def update
        @board = Board.find(params[:id])
        
        if @board.update(board_params)
            redirect_to @board
        else
            render 'edit'
        end
        
    end
    # After deletion, serves up parent board
    def destroy
        swap = Board.find(params[:id])
        @board = Board.find(swap.parent.id)
        swap.destroy
        
        redirect_to @board
    end
    
    private
    def board_params
        params.require(:board).permit(:name, :description, :parent_id )
    end
    
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/edit.html.erb
<%= form_for(@board) do |f| %>

    <%= f.text_field :name %>
    <br/>
    <%= f.text_area :description %>
    <br/>
    <%= f.hidden_field  :parent_id, :value => @board.parent.id %>
    <%= f.submit %>
<% end %> 

app/views/boards/index.html.erb
<% content_for :header_left  do %>
    <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user), class: "button" %>
        <a class="button" data-method="delete" href= <%=logout_path%> >Log out</a>
    <% end %>
<% end %>

<% content_for :header_title  do %>
    <h1><%= @board.name %></h1>
        <%= @board.description %>
<% end %>

<% content_for :header_right  do %>
    <% if logged_in? %>
        <a class="icon" href= "http://www.google.com" >NT</a>
    <% end %>
    <a class="icon" href= <%=new_board_path( :parent_id => @board.id )%> >NS</a>
<% end %>
<%= render 'layouts/header' %>

<div class="content_field">
    <div class="sidebar_container left">
        <div class="sidebar left"></div>
    </div>
    <div class="content_container">
        <% if @board.children.any? %>
            <div class="tile no_border">
                <% @board.children.each do |child| %>
                    <a class="list_item" href=<%=board_path(child)%>>
                        <h3 class="content_division"><%= child.name %></h3>
                        <div class="content_division"><%= child.description %></div>
                        <!--<%= link_to 'edit', edit_board_path( child ), class: "button" %>
                        <%= link_to 'delete', board_path( child ),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %>-->
                    </a>
                <% end %>
            </div>
        <% end %>
        
        <% if @topics.any? %>
            <div class="tile no_border">
                <% @topics.each do |topic| %>
                    <a class="list_item" href=<%=topic_post_path(topic)%>>
                        <h3 class="content_division">A POST</h3>
                        <div class="content_division"><%= topic.content %></div>
                    </a>
                <% end %>
            </div>
        <% end %>
        
    </div>
    <div class="sidebar_container right">
        <div class="sidebar right"></div>
    </div>
</div>

app/views/boards/new.html.erb
<%= form_for(@board) do |f| %>

    <%= f.text_field :name %>
    <br/>
    <%= f.text_area :description %>
    <br/>
    <%= f.hidden_field  :parent_id, :value => @parent_id %>
    <%= f.submit %>
<% end %> 

app/views/boards/show.html.erb
<% content_for :header_left  do %>
    <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user), class: "button" %>
        <a class="button" data-method="delete" href= <%=logout_path%> >Log Out</a>
    <% end %>
<% end %>

<% content_for :header_title  do %>
    <h1><%= @board.name %></h1>
        <%= @board.description %>
<% end %>

<% content_for :header_right  do %>
    
    <%= link_to "NS", new_board_path( :parent_id => @board.id ), class: "icon" %>
    <%= link_to "E",  edit_board_path( @board ), class: "icon" %>
    <%= link_to "H", boards_path, class: "icon" %>
    <!--<a class="icon" href= <%=new_board_path( :parent_id => @board.id )%> >NS</a>
    <a class="icon" href= <%=edit_board_path( @board )%> >E</a>
    <a class="icon" data-method="delete" href= <%=edit_board_path( @board )%> >D</a>
    <a class="icon" href= <%=boards_path%> >H</a>-->
<% end %>

<%= render 'layouts/header' %>


<div class="content_field">
    <div class="sidebar_container left">
        <div class="sidebar left"></div>
    </div>
    <div class="content_container">
        <% if @board.children.any? %>
            <div class="tile no_border">
                <% @board.children.each do |child| %>
                    <a class="list_item" href=<%=board_path(child)%>>
                        <h3 class="content_division"><%= child.name %></h3>
                        <div class="content_division"><%= child.description %></div>
                        <!--<%= link_to 'edit', edit_board_path( child ), class: "button" %>
                        <%= link_to 'delete', board_path( child ),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %>-->
                    </a>
                <% end %>
            </div>
        <% end %>
        
        <% if @topics.any? %>
            <div class="tile no_border">
                <% @topics.each do |topic| %>
                    <a class="list_item" href=<%=topic_post_path(topic)%>>
                        <h3 class="content_division">A POST</h3>
                        <div class="content_division"><%= topic.content %></div>
                    </a>
                <% end %>
            </div>
        <% end %>
    </div>
    <div class="sidebar_container right">
        <div class="sidebar right"></div>
    </div>
</div>

<!--<%= link_to 'delete', board_path( @board ),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>-->