config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get       'login'     => 'sessions#new'
  post      'login'     => 'sessions#create'
  delete    'logout'    => 'sessions#destroy'
  get       'main_page/home'
  get       'main_page/sign_in', as: 'sign_in_main_page'

  resources :boards
  resources :users
  resources :topic_posts
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
    

  root 'main_page#home'

  

end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  def home
  end

  def sign_in
  end
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/main_page/home.html.erb
<% content_for :header_left  do %>
    <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user), class: "button" %>
    <% end %>
<% end %>

<% content_for :header_title  do %>
    <h1>Welcome to the Forum</h1>
<% end %>

<% content_for :header_right  do %>
<% end %>
<%= render 'layouts/header' %>

<div class="content_field">
    <div class="sidebar_container left">
        <div class="sidebar left"></div>
    </div>
    <div class="content_container">
        <div class="tile content" id="about">
            About the forum
        </div>
        <a class="tile content" id="signup" href=<%=login_path%> >
            sign in
        </a>
    </div>
    <div class="sidebar_container right">
        <div class="sidebar right"></div>
    </div>
</div>

<br/>

app/views/main_page/sign_in.html.erb
<div class="tile wide">

<h1 class="label"> Sign In </h1>
<p>
Fields will go here.
</p>
<%= link_to 'New Account', new_user_path, class: "btn_blank label" %>
</div>